Add support for readonly select3?
datavisyn/tdp_core pull request #601
Opened 2021-12-16 10:50 UTC by oltionchampari

The issue is that in comments, we propagate the `readonly ` props to select3 and select 3 does not do anything with it
I saw here that https://github.com/select2/select2/issues/3387#issuecomment-281481067 that readonly is not supported
by default.

This PR is a suggestion on how that could work, but two issues are still present you can still open the select dropdwon by tabbing to it and of course not all tags are visible or scrollable if the content overflows.

 @puehringer what do you think, do you know a better/ easier solution should support this at all?
 We do not need this feature currently if it is hard to implement

2021-12-16 11:10 UTC, puehringer requested changes

2021-12-16 11:10 UTC, puehringer commented on src/form/elements/Select3.ts
> +     readonly: boolean;
Indentation is slightly off. 

This PR is fine for me, but I would not invest much more time in it. We are going to refactor tdp_comments to use `react-select` at some point, which makes most of the adjustments obsolete.

2021-12-17 08:34 UTC, oltionchampari commented
Added also the disabled option to select3

2021-12-17 12:54 UTC, puehringer approved these changes

2021-12-17 13:04 UTC, merged