Different aggregation types in bar chart
datavisyn/tdp_core pull request #687
Opened 2022-04-04 22:55 UTC by dvzacharycutler

Adding different aggregation types in bar charts. Creating a new UI dropdown for aggregation type, followed by a aggregation column selector for all of the aggregation types except for count. Also disabled those aggregate types if there arent any numerical columns, with an info icon explaining why. 

Also has some changes to ensure that the vis component is never rendering an inconsistent visConfig object, which it previously was for one render after changing types. 

Also one small change in useAsync to ensure useAsync doesnt throw errors if the component gets unmounted in the middle of the async call

https://user-images.githubusercontent.com/87644761/161645338-ef011aa9-69e1-4104-95c3-9646c1fb01ea.mp4

2022-04-08 16:35 UTC, thinkh requested changes
Thanks for this nice feature. Please see my comments below.

2022-04-08 16:35 UTC, thinkh commented on src/vis/bar/utils.ts
> +  );
Please refactor accordingly.

2022-04-08 16:35 UTC, thinkh commented on src/vis/bar/utils.ts
> +  aggregateColumn: VisNumericalColumn,
```suggestion
  aggregateType: EAggregateTypes,
  aggregateColumn: VisNumericalColumn,
```

Why one is abbreviated and one not?

2022-04-08 16:35 UTC, thinkh commented on src/vis/bar/utils.ts
> +  aggregateColumn: VisNumericalColumn | null,
```suggestion
  aggregateType: EAggregateTypes,
  aggregateColumn: VisNumericalColumn | null,
```

2022-04-08 16:35 UTC, thinkh commented on src/vis/bar/utils.ts
> +  aggColumn: VisNumericalColumn,
```suggestion
  aggregateType: EAggregateTypes,
  aggregateColumn: VisNumericalColumn,
```

2022-04-08 16:35 UTC, thinkh commented on src/vis/bar/utils.ts
> +  aggColumn: VisNumericalColumn,
```suggestion
  aggregateType: EAggregateTypes,
  aggregateColumn: VisNumericalColumn,
```

Name equal parameters equal also across functions.

2022-04-08 16:35 UTC, thinkh commented on src/vis/Vis.tsx
> +  // TODO:: probably change the names, especially "current" and "inconsistentVisConfig" to something more useful.
From the state properties, I would either expect something like `consistent` + `inconsistent` or `current` + `previous`. If they are matching you could also name your local variables `visConfig` and `inconsistentVisConfig`.

In general, however, we should try to solve the root of the inconsistent vis config. @puehringer do you have an idea if there is still some issue with our vis config setup?

2022-04-11 14:03 UTC, dvzacharycutler commented on src/vis/bar/utils.ts
> +  );
This is great!

2022-04-12 14:05 UTC, thinkh commented on src/vis/Vis.tsx
> +  // TODO:: probably change the names, especially "current" and "inconsistentVisConfig" to something more useful.
We agreed in a chat that we will keep the solution for now as it is and might refactor it later with issue https://github.com/datavisyn/reprovisyn/issues/304.

2022-04-12 14:05 UTC, thinkh approved these changes

2022-04-12 14:05 UTC, merged