CLUE support for URL query parameter + rewrite hash prameters
datavisyn/tdp_core pull request #762
Opened 2022-08-01 13:49 UTC by thinkh

2022-08-03 07:03 UTC, thinkh commented
@puehringer Please review the code. If you like you can also test it in one of your apps, but the default behavior hasn't changed.

@oltionchampari Please test the functionality with Ordino in combination with https://github.com/Caleydo/ordino/pull/419 and https://github.com/Caleydo/ordino_public/pull/142.

2022-08-03 08:28 UTC, oltionchampari requested changes
I noticed two minor things in the compiler. Did not look at the rest of the code

2022-08-03 08:28 UTC, oltionchampari commented on src/ATDPApplication.ts
> +  cluePropertyHandler?: 'hash';
```suggestion
  cluePropertyHandler?: 'hash' | 'query';
```

2022-08-03 08:28 UTC, oltionchampari commented on src/ATDPApplication.ts
> +  clueRewriteOtherProperty?: false;
```suggestion
  clueRewriteOtherProperty?: boolean;
```

2022-08-08 07:52 UTC, thinkh commented on src/ATDPApplication.ts
> +  cluePropertyHandler?: 'hash';
Thanks for pointing out. Fixed.

2022-08-08 07:52 UTC, thinkh commented on src/ATDPApplication.ts
> +  clueRewriteOtherProperty?: false;
Thanks for pointing out. Fixed.

2022-08-11 05:43 UTC, puehringer approved these changes

2022-08-11 06:49 UTC, thinkh commented
@oltionchampari I addressed all your points. Could you please have another look at the PRs and approve them so that we can proceed with the merge?

2022-08-11 09:23 UTC, oltionchampari approved these changes
Everything in order now

2022-08-11 09:23 UTC, merged

2022-08-11 09:25 UTC, oltionchampari commented
Had a conversation with @thinkh and decided to merge