Zc/mantine hexbin
datavisyn/tdp_core pull request #790
Opened 2022-09-21 12:37 UTC by dvzacharycutler

Closes *list issues numbers here*

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- 

### Screenshots

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2022-10-13 13:04 UTC, thinkh requested changes
Awesome new visualization. It looks already very good. Please see my comments below.

- [ ] The mouse while should work in 

If no numerical columns are selected the message currently takes the full height of the vies view (should be only the height of the text). 

![image](https://user-images.githubusercontent.com/5851088/195598816-b4ffa88d-8638-4ab5-8bfe-1fde2bf10bfe.png)

- [x] Hexbin plot (sentence case)
- [x] Invalid settings (sentence case)
- [x] Convert invalid settings card to [Mantine info alert](https://mantine.dev/core/alert/) (currently bootstrap)
   - Also for all other cards and visualizations
- [x] Horizontally center the info alert
- [x] Hexbin options (sentence case)
   ![image](https://user-images.githubusercontent.com/5851088/195599816-c31fb0b7-992a-473f-952c-536d1cfd9594.png)
- [x] Add tooltips to brush option buttons
   ![image](https://user-images.githubusercontent.com/5851088/195600359-ce2fc262-29a2-4b27-94e3-cff7d06a980f.png)
- [ ] Enable zoom with mouse wheel in brush mode (currently, it only works in pan mode)
- [ ] Make list of categories in legend scrollable
   ![image](https://user-images.githubusercontent.com/5851088/195600953-3be4336a-ed34-42ea-ae27-b61a2b88f042.png)

2022-10-13 13:04 UTC, thinkh commented on src/vis/hexbin/Hexplot.tsx
> +  // differently than if i use style to do so
Sorry, I don't understand.

2022-10-13 13:04 UTC, thinkh commented on src/vis/hexbin/PieChart.tsx
> +        // eslint-disable-next-line react/no-array-index-key
See https://blog.logrocket.com/12-essential-eslint-rules-react/#react-no-array-index-key and https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md.

2022-11-02 09:35 UTC, dvzacharycutler commented on src/vis/hexbin/Hexplot.tsx
> +      const max = d3v7.max(hexes.map((h) => h.length));
done

2022-11-02 09:35 UTC, dvzacharycutler commented on src/vis/hexbin/Hexplot.tsx
> +      const max = d3v7.max(hexes.map((h) => h.length));
done

2022-11-02 09:36 UTC, dvzacharycutler commented on src/vis/hexbin/HexbinVisSidebar.tsx
> +        {/* <HexbinOptionSelect callback={(hexbinOptions: EHexbinOptions) => setConfig({ ...config, hexbinOptions })} currentSelected={config.hexbinOptions} /> */}
done

2022-11-02 15:54 UTC, dvzacharycutler commented on src/vis/sidebar/HexbinOptionSelect.tsx
> +  return <Select label="Hexbin Options" onChange={(e) => callback(e as EHexbinOptions)} data={options} value={currentSelected} />;
done

2022-11-03 08:43 UTC, thinkh requested changes
@dvzacharycutler Thanks for your bug fixes. It works now much better. I still found a few inconsistencies that should be removed before merging this PR.

### Steps to reproduce

1. Select hexbin plot
2. Remove all columns

### Observed behavior

The message shows `Scatterplot`.

![grafik](https://user-images.githubusercontent.com/5851088/199671040-21f4cc75-2f48-4ed3-9840-e5af01b6b7d2.png)

### Expected behavior

1. The message should mention the _Hexbin plot_ when this plot is selected
2. Consistent spelling: _Scatter plot_ vs. _Scatterplot_

2022-11-07 11:25 UTC, thinkh requested changes
@dvzacharycutler I tested this branch with Ordino public in a local workspace and found a couple of problems. The problems might be related to  #786 and not specifically to this PR. You can decide where to fix it.

Here an overview of the interaction with the general visualization of this branch:

[ordino-hexbin.webm](https://user-images.githubusercontent.com/5851088/200290986-db662af6-4482-458e-b8d6-f3a8a97c90bf.webm)

### Scatter plot: Opacity does not have an effect

Sometimes the opacity slider does not have any effect.
 
![ordino-scatter-opacity-0](https://user-images.githubusercontent.com/5851088/200291203-f62a4cd3-775f-4950-aaa8-4e8d977f5189.png)

![ordino-scatter-opacity-1](https://user-images.githubusercontent.com/5851088/200291213-705956f8-7399-4106-bb2e-2ee2583f8056.png)

As you can see in the video above, it worked somehow after playing around and switching visualization. But it does not work when I opened it the first time (see screenshots).

### Scatter plot: Legend overlaying visualization

The legend is overlaying the visualization and makes it impossible to use. Could be a flex problem in Ordino?

![ordino-scatter-overplotting](https://user-images.githubusercontent.com/5851088/200291413-99dcf473-8978-4b07-9b90-1651513bdbd6.png)

### Hexbin plot: Wrong options panel position

When switching to hexbin plot the options panel is positioned absolute to the window and not the visualization container. (This does not happen for the other visualizations.) After closing and opening the panel again it is positioned correctly. 

Furthermore the hexbin plot is empty which should be the case because the scatter plot shows data.

![ordino-broken-hexbin](https://user-images.githubusercontent.com/5851088/200291822-771e6a5a-c7f2-4bec-8407-6abbf82fe340.png)

### Various plots: scroll position and options panel

For all plot types the visualization is positioned far to the right which requires to scroll to the right. Then the options panel is positioned somewhere in the center.

![ordino-stripplot-scrolling](https://user-images.githubusercontent.com/5851088/200298664-71429060-3311-4beb-8dd4-f4f44caa83b5.png)

![ordino-stripplot-scrolling-options-open](https://user-images.githubusercontent.com/5851088/200298676-3919180c-202b-4523-9eb4-92791d7dbf35.png)

2022-11-07 11:56 UTC, thinkh commented
In addition, I saw now that the options panel is also overlaying the Ordino start menu.

![image](https://user-images.githubusercontent.com/5851088/200304325-ef22f3b3-0d86-4075-8f4e-0c6dc36309c3.png)

2023-02-03 13:23 UTC, thinkh approved these changes
Thanks for the fixes. Looks good to me.

2023-02-03 13:30 UTC, merged